// This file is generated by scripts/generate-skills-data.mjs. Do not edit by hand.

export type SkillRecord = {
  name: string
  description: string
  sourceId: string
  sourceLabel: string
  sourceType: 'local' | 'user' | 'system'
  folder: string
  skillPath: string
  referencesCount: number
  scriptsCount: number
  agentsCount: number
}

export type SkillSource = {
  id: string
  label: string
  type: 'local' | 'user' | 'system'
  root: string
  count: number
  skills: SkillRecord[]
}

export const skillSources: SkillSource[] = [
  {
    "id": "claude",
    "label": "Claude",
    "type": "local",
    "root": "~/.claude/skills",
    "count": 1,
    "skills": [
      {
        "name": "saas-starter",
        "description": "Bootstrap a production-ready TanStack Start SaaS project from scratch and deploy it to Railway, Vercel, or Cloudflare Pages — fully automated. Invoke when the user says things like \"帮我建一个新项目\", \"new saas project\", \"bootstrap a project\", \"用这个 skill开新项目\", \"start a new tanstack project\", or similar. The skill first collects a variable checklist from the user, then works autonomously: scaffold → configure → push DB schema → set env vars → deploy. Do not stop partway through unless a required variable is genuinely missing.",
        "sourceId": "claude",
        "sourceLabel": "Claude",
        "sourceType": "local",
        "folder": "saas-starter",
        "skillPath": "~/.claude/skills/saas-starter/SKILL.md",
        "referencesCount": 0,
        "scriptsCount": 0,
        "agentsCount": 0
      }
    ]
  },
  {
    "id": "codex-user",
    "label": "Codex",
    "type": "user",
    "root": "~/.codex/skills",
    "count": 3,
    "skills": [
      {
        "name": "openclaw-feishu-install",
        "description": "Install, repair, and verify an OpenClaw Feishu bot. Use when configuring a new Feishu gateway, fixing secret/provider issues, updating allowlists, renaming a bot workspace, or restarting and validating the gateway after Feishu changes.",
        "sourceId": "codex-user",
        "sourceLabel": "Codex",
        "sourceType": "user",
        "folder": "openclaw-feishu-install",
        "skillPath": "~/.codex/skills/openclaw-feishu-install/SKILL.md",
        "referencesCount": 0,
        "scriptsCount": 0,
        "agentsCount": 1
      },
      {
        "name": "project-stoploss-review",
        "description": "Use when Codex needs to review why a product, MVP, prototype, or side project failed, decide whether to stop/continue/restart it, or extract reusable lessons before starting the next project. Triggers include postmortems, \"why did this project fail\", \"should I keep going\", \"what should I do differently next time\", and requests to turn one failed project into a reusable checklist or operating rule.",
        "sourceId": "codex-user",
        "sourceLabel": "Codex",
        "sourceType": "user",
        "folder": "project-stoploss-review",
        "skillPath": "~/.codex/skills/project-stoploss-review/SKILL.md",
        "referencesCount": 1,
        "scriptsCount": 0,
        "agentsCount": 1
      },
      {
        "name": "works-project-status",
        "description": "Inspect projects under ~/Works and summarize current development status. Use when Codex needs to answer questions like \"What projects are in ~/Works?\", \"What am I actively working on?\", \"Which repos are dirty, clean, or stale?\", or \"Show the current status of project X under ~/Works\".",
        "sourceId": "codex-user",
        "sourceLabel": "Codex",
        "sourceType": "user",
        "folder": "works-project-status",
        "skillPath": "~/.codex/skills/works-project-status/SKILL.md",
        "referencesCount": 0,
        "scriptsCount": 1,
        "agentsCount": 1
      }
    ]
  },
  {
    "id": "codex-system",
    "label": "Codex System",
    "type": "system",
    "root": "~/.codex/skills/.system",
    "count": 5,
    "skills": [
      {
        "name": "imagegen",
        "description": "Generate or edit raster images when the task benefits from AI-created bitmap visuals such as photos, illustrations, textures, sprites, mockups, or transparent-background cutouts. Use when Codex should create a brand-new image, transform an existing image, or derive visual variants from references, and the output should be a bitmap asset rather than repo-native code or vector. Do not use when the task is better handled by editing existing SVG/vector/code-native assets, extending an established icon or logo system, or building the visual directly in HTML/CSS/canvas.",
        "sourceId": "codex-system",
        "sourceLabel": "Codex System",
        "sourceType": "system",
        "folder": "imagegen",
        "skillPath": "~/.codex/skills/.system/imagegen/SKILL.md",
        "referencesCount": 5,
        "scriptsCount": 2,
        "agentsCount": 1
      },
      {
        "name": "openai-docs",
        "description": "Use when the user asks how to build with OpenAI products or APIs and needs up-to-date official documentation with citations, help choosing the latest model for a use case, or model upgrade and prompt-upgrade guidance; prioritize OpenAI docs MCP tools, use bundled references only as helper context, and restrict any fallback browsing to official OpenAI domains.",
        "sourceId": "codex-system",
        "sourceLabel": "Codex System",
        "sourceType": "system",
        "folder": "openai-docs",
        "skillPath": "~/.codex/skills/.system/openai-docs/SKILL.md",
        "referencesCount": 3,
        "scriptsCount": 1,
        "agentsCount": 1
      },
      {
        "name": "plugin-creator",
        "description": "Create and scaffold plugin directories for Codex with a required `.codex-plugin/plugin.json`, optional plugin folders/files, valid manifest defaults, and personal-marketplace entries by default. Use when Codex needs to create a new personal plugin, add optional plugin structure, generate or update marketplace entries for plugin ordering and availability metadata, or update an existing local plugin during development with the CLI-driven cachebuster and reinstall flow.",
        "sourceId": "codex-system",
        "sourceLabel": "Codex System",
        "sourceType": "system",
        "folder": "plugin-creator",
        "skillPath": "~/.codex/skills/.system/plugin-creator/SKILL.md",
        "referencesCount": 2,
        "scriptsCount": 4,
        "agentsCount": 1
      },
      {
        "name": "skill-creator",
        "description": "Guide for creating effective skills. This skill should be used when users want to create a new skill (or update an existing skill) that extends Codex's capabilities with specialized knowledge, workflows, or tool integrations.",
        "sourceId": "codex-system",
        "sourceLabel": "Codex System",
        "sourceType": "system",
        "folder": "skill-creator",
        "skillPath": "~/.codex/skills/.system/skill-creator/SKILL.md",
        "referencesCount": 1,
        "scriptsCount": 3,
        "agentsCount": 1
      },
      {
        "name": "skill-installer",
        "description": "Install Codex skills into $CODEX_HOME/skills from a curated list or a GitHub repo path. Use when a user asks to list installable skills, install a curated skill, or install a skill from another repo (including private repos).",
        "sourceId": "codex-system",
        "sourceLabel": "Codex System",
        "sourceType": "system",
        "folder": "skill-installer",
        "skillPath": "~/.codex/skills/.system/skill-installer/SKILL.md",
        "referencesCount": 0,
        "scriptsCount": 3,
        "agentsCount": 1
      }
    ]
  }
] as const

export const allSkills: SkillRecord[] = skillSources.flatMap((source) => source.skills)
